### ISSUE TITLE
Newsletter de 29/06/2017

### ISSUE THREAD

**Issue by henriquebastos** [henriquebastos/curtocircuito#1]
Newsletter a ser disparada no dia 29/06/2017

Poste sua dica, link ou sugestão aqui nos comentários desta issue.
Ao longo da semana vamos debatendo, votando e juntando os melhores links que serão inseridos na próxima newsletter.

##Template para uma boa dica (Não é obrigatório, faça como quiser):

```
**[Título](URL)**
Rápida descrição
```

Mete ficha! ;)

**Comment by henriquebastos** [comment]
O @agoulart reuniu uma série de links interessantes [aqui neste Google Docs](https://docs.google.com/document/d/1WaRs2XAKsCTrc9j_60IfNXmMIuDShZ3gByXSAR3jhqs/edit).

Seria massa cada um ver o que achou maneiro e trazer pra cá o link incluindo uma breve descrição. Tenha sempre em mente que o propósito é facilitar o leitor se vale ou não abrir o link. ;)

**Comment by Riverfount** [comment]
## URL's do Vídeo M3A08 sobre boas práticas para nomea URL's

**[Cool URIs don’t change](http://www.w3.org/Provider/Style/URI.html)***
 
**[The user interface of URLs](http://www.isoc.org/inet95/proceedings/PAPER/016/html/paper.html)**
 
**[URL as UI](https://www.nngroup.com/articles/url-as-ui)**
 
**[HTTP url path parameter syntax](http://doriantaylor.com/policy/http-url-path-parameter-syntax)**
 
**[What Every Developer Should Know About URLs](http://www.skorks.com/2010/05/what-every-developer-should-know-about-urls)**

**Comment by henriquebastos** [comment]
**[Instagram makes a smooth mode to Python 3](https://thenewstack.io/instagram-makes-smooth-move-python-3/)**
Entrevista com 2 engenheiros do Instagram sobre a decisão e estratégia de migrar do Python 2 para o Python 3.

**Comment by henriquebastos** [comment]
**[The new f-strings in Python 3.6](https://cito.github.io/blog/f-strings/)**
Entenda a utilidade das _f-strings_, um novo recurso sintático do Python 3.6.

**Comment by henriquebastos** [comment]
**[Why using a context-manager is a better choice?](https://medium.com/@sinister/https-medium-com-sinister-why-using-a-context-manager-is-a-better-choice-55ccfcecddb8)**
Aprenda como funcion o comando `with` do Python e como ele te ajuda a fazer um código melhor.

**Comment by henriquebastos** [comment]
**[Understanding Asynchronous Programming in Python](https://dbader.org/blog/understanding-asynchronous-programming-in-python)**
Um guia completo passo à passo para você entender como funciona programação assíncrona em Python.

**Comment by henriquebastos** [comment]
**[django-admin-env-notice](https://github.com/dizballanze/django-admin-env-notice)**
Evite erros identificando visualmente na interface do seu Django Admin se você está no ambiente de desenvolvimento ou produção.

**Comment by kerollaine** [comment]
**[DevOps: processo, cultura e carreira](https://medium.com/opensanca/devops-processo-cultura-e-carreira-5648f5e0be08)**
Carreira, processo ou cultura? Entenda o que é DevOps.

**Comment by agoulartx** [comment]
[**Enriching Your Python Classes With Dunder (Magic, Special) Methods**](https://dbader.org/blog/python-dunder-methods)
What Python’s “magic methods” are and how you would use them to make a simple account class more Pythonic.

**Comment by agoulartx** [comment]
[**Build beautiful web-based interfaces in Python**](https://plot.ly/products/dash/)
Dash is a Python framework for building analytical web applications. No JavaScript required.

**Comment by agoulartx** [comment]
[**Explore a better way of creating APIs**](http://graphene-python.org/)
Graphene is a Python library for building APIs with GraphQL easily. It provides an alternative to REST and ad-hoc webservice architectures.

**Comment by agoulartx** [comment]
[**Deal or no deal? Training AI bots to negotiate**](https://code.facebook.com/posts/1686672014972296/deal-or-no-deal-training-ai-bots-to-negotiate/)
Today, researchers at Facebook Artificial Intelligence Research (FAIR) have open-sourced code and published research introducing dialog agents with a new capability — the ability to negotiate.

**Comment by agoulartx** [comment]
[**Não tenha medo daquilo que não conhece**](http://www.agoulart.com/2017-06-20-nao-tenha-medo-do-que-nao-conhece/)
Mesmo fazendo o que gosta, seu cérebro pode te bloquear.

**Comment by agoulartx** [comment]
[**How to get data from Google Analytics with Python in Jupyter Notebook**](https://read.dataly.co/google-analytics-api-how-to-get-data-from-google-analytics-with-python-in-jupyter-notebook-with-85483dd73e22)
Today I found an online tool that can get the stats of the published articles from Google Analytics.

**Comment by agoulartx** [comment]
[**Building an API with Django REST Framework and Class-Based Views**
](https://medium.com/@ktruong008/building-an-api-with-django-rest-framework-and-class-based-views-75b369b30396)
With the rise of Single-Page-Applications and the trend of separating monoliths into services with distinct front and backends, knowing how to make your own RESTful API for your backend is more important than ever.

**Comment by agoulartx** [comment]
[**Celery 4 Periodic Task in Django**](https://medium.com/@yehandjoe/celery-4-periodic-task-in-django-9f6b5a8c21c7)
Automation in Django is a developer dream. Tedious work such as creating database backup, reporting annual KPI, or even blasting email could be made a breeze. Through Celery — a well-known software in Python for delegating task — such action made possible.

**Comment by agoulartx** [comment]
[**Getting started with translating a Django Application**](https://blog.braham.biz/getting-started-with-translating-a-django-application-d85ec34e505)
Recently I found out how to quickly bootstrap translation for your application to different languages. On of the things that amazed me about the Django platform, that it will automatically load the correct translation file based on the browser language.

**Comment by juniorcarvalho** [comment]
Alternativa ao heroku. 
http://pythonclub.com.br/deploy-rapido-simples-com-dokku.html

...olha o jabá....

**Comment by Lrcezimbra** [comment]
**[Usando um Bot do Telegram para receber notificações](http://eltonminetto.net/post/2017-06-13-usando-bot-telegram/)**
Integração do Telegram com Trello, Gitlab, Bitbucket, GitHub e envio de mensagem através de uma requisição POST. Ex.: `curl -X POST -d '{"text":"Mensagem Teste"}' https://integram.org/abcdefghi`

**Comment by christophermoura** [comment]
[Test Driven Development of a Django RESTful API](https://realpython.com/blog/python/test-driven-development-of-a-django-restful-api/)

Artigo que apresenta o processo de desenvolvimento de uma API RESTful baseada em CRUD com Django e o Django REST Framework, que é usado para construir APIs RESTful baseada em Django models de forma rápida. (_em inglês_)

**Comment by agoulartx** [comment]
[**How to Write a Git Commit Message**](https://chris.beams.io/posts/git-commit/)

Nesse artigo o autor fala sobre a importancia em se escrever boas mensagens de commit, como isso pode ajudar ao longo do projeto e ainda dá algunas dicas e exemploas de boas práticas.

**Comment by agoulartx** [comment]
[**Linked Lists in Python**](https://dbader.org/blog/python-linked-list)
Learn how to implement a linked list data structure in Python, using only built-in data types and functionality from the standard library.

**Comment by agoulartx** [comment]
[**Getting started with translating a Django Application**](https://blog.braham.biz/getting-started-with-translating-a-django-application-d85ec34e505)

I recently started learning the Django Python framework. So far I really like it. Recently I found out how to quickly bootstrap translation for your application to different languages.

**Comment by agoulartx** [comment]
**Mandem os próximos links na nova issue:**
[Newsletter Edição 2](https://github.com/henriquebastos/curtocircuito/issues/2)
