### ISSUE TITLE
Newsletter Edição 2

### ISSUE THREAD

**Issue by henriquebastos** [henriquebastos/curtocircuito#2]
Poste sua dica, link ou sugestão aqui nos comentários desta issue.
Ao longo da semana vamos debatendo, votando e juntando os melhores links que serão inseridos na próxima newsletter.

A ideia é você compartilhar aquele link que a galera não pode ficar sem ler. ;)

##Template para uma boa dica (Não é obrigatório, faça como quiser):

**[Título](URL)**
Rápida descrição
Mete ficha! ;)

**Comment by agoulartx** [comment]
[**SCRUM**](http://www.desenvolvimentoagil.com.br/scrum/)
Entenda o que é SCRUM e como melhorar sua relação com o cliente em projetos ágeis.

**Comment by leonardocintra** [comment]
Dicas de Django Formset Avançado
Usando CreateView, UpdateView etc, explicando o que é o `extra=0, extra=1, etc`

**Comment by leviplj** [comment]
[65 dicas para ser um programador melhor](https://willianjusten.com.br/65-dicas-para-ser-um-programador-melhor/)
Dicas para ser um programador melhor.

**Comment by Lrcezimbra** [comment]
@leonardocintra faltou o link

> Dicas de Django InlineFormset Avançado
> Usando CreateView, UpdateView etc, explicando o que é o extra=0, extra=1, etc

**Comment by Lrcezimbra** [comment]
**[Django project optimization guide (part 1)](http://dizballanze.com/django-project-optimization-part-1/)**
Profiling e logging para projetos Django.

**[Django project optimization guide (part 2)](http://dizballanze.com/django-project-optimization-part-2/)**
Boas práticas para otimizar queries usando o ORM do Django.

**Comment by gilsondev** [comment]
[**How to manage concurrency in Django models**](https://medium.com/@hakibenita/how-to-manage-concurrency-in-django-models-b240fed4ee2)

[**Lessons from scale: Django**](https://sanketsaurav.com/lessons-from-scale-django-124f7b16ae0c)

**Comment by leviplj** [comment]
[Pesquisadores criam celular que não precisa de bateria](https://olhardigital.com.br/noticia/pesquisadores-criam-celular-que-nao-precisa-de-bateria/69595)
Uma equipe com engenheiros elétricos e cientistas da computação da Universidade de Washington desenvolveu um celular que não depende de bateria para funcionar.

**Comment by leviplj** [comment]
[**Building CSS Games**](https://www.youtube.com/watch?v=lxUK6gCtSg0)
Construindo um jogo utilizando apenas CSS.

[**Using Node.js To Create Electronic Dance Music**](https://www.youtube.com/watch?v=dIiwFzFvsmw)
Criando música eletrônica utilizando Node.js + scribbletune (lib)

**Comment by agoulartx** [comment]
[How to Write a Git Commit Message](https://chris.beams.io/posts/git-commit/)
Entenda a importancia de um histórico de boas mensagens de commit.

**Comment by Lrcezimbra** [comment]
**[🌟 Introducing Dash 🌟](https://medium.com/@plotlygraphs/introducing-dash-5ecf7191b503)**
Create Reactive Web Apps in pure Python

**Comment by edmilton** [comment]
[Estimates are Promises - A Better Metaphor](http://www.akitaonrails.com/2017/06/26/estimates-are-promises-a-better-metaphor)
Artigo sobre escopo aberto, antifragile, estimativas.

**Comment by augustogoulart** [comment]
[f-strings: fun strings, fast string](https://augustogoulart.me/f-strings-fun-strings-fast-string.html)
Artigo explicando sobre as novas f-strings do Python 3.6, suas vantagens e cuidados a tomar.

**Comment by henriquebastos** [comment]
Newsletter agendada. :)
