### ISSUE TITLE
Newsletter Edição 3

### ISSUE THREAD

**Issue by henriquebastos** [henriquebastos/curtocircuito#3]
Poste sua dica, link ou sugestão aqui nos comentários desta issue.
Ao longo da semana vamos debatendo, votando e juntando os melhores links que serão inseridos na próxima newsletter.

A ideia é você compartilhar aquele link que a galera não pode ficar sem ler. ;)

##Template para uma boa dica (Não é obrigatório, faça como quiser):

**[Título](URL)**
Rápida descrição
Mete ficha! ;)

**Comment by inaciomdrs** [comment]
[Introdução à Programação Funcional (com Python)](https://maryrosecook.com/blog/post/a-practical-introduction-to-functional-programming)
Como trabalhar com técnicas básicas e fundamentais de programação funcional usando Python (neste artigo, eles usam Python 2).

**Comment by gilsondev** [comment]
[Airflow: a workflow management platform](https://medium.com/airbnb-engineering/airflow-a-workflow-management-platform-46318b977fd8)

**Comment by morenopc** [comment]
[Fairphone 2](https://www.fairphone.com/en/)
O primeiro smartphone ético e modular do mundo. A ideia é ter um smartphone que pode ser consertado e melhorado com facilidade. Pena que o preço ainda é bem alto e está somente disponível na Europa.

**Comment by Riverfount** [comment]
[Guia para Deploy Django](http://fernandofreitasalves.com/guia-para-deploy-django-python/)

Guia Definitivo Rápido, ou não tão rápido, para fazer Deploy Django com Python 3. É um deploy para Kids.

**Comment by thiagorossener** [comment]
[Como migrar seus posts do Wordpress para o Jekyll de um jeito simples](https://www.rossener.com/como-migrar-seus-posts-do-wordpress-para-o-jekyll/)

Um script para migrar seus posts do Wordpress para o Jekyll sem dores de cabeça.

**Comment by augustogoulart** [comment]
[Refactoring with tests in Python: a practical example](http://blog.thedigitalcatonline.com/blog/2017/07/21/refactoring-with-test-in-python-a-practical-example/#.WYB776yGOis)
Um passo-a-passo de uma sessão de refatoração de código guiada por testes.

**Comment by augustogoulart** [comment]
[Django Anti-Patterns: Signals](https://lincolnloop.com/blog/django-anti-patterns-signals/)
Os Signals no Django são uma feature poderosa, e com grandes poderes vem grandes responsabilidades.

**Comment by augustogoulart** [comment]
[Django memory leaks I](http://blog.gingerlime.com/2011/django-memory-leaks-part-i/)
[Django memory leaks II](http://blog.gingerlime.com/2011/django-memory-leaks-part-ii/)
Nesta séria de artigos, entenda melhor como o Django usa a memória do seu servidor e onde é possível interferir.

**Comment by cuducos** [comment]
Nutrição para atletas de alto desempenho (naipe olimpíadas, NFH, UFC…):

* [TEDx](https://www.youtube.com/watch?v=Jqpjap8rewo)
* [Livro (en_US)](https://www.amazon.com/Thrive-Diet-Paperback-Brendan-Brazier/dp/B000P0RCS8)

_Spoiler: plant-base diet_ ; )

**Comment by Riverfount** [comment]
[Cookiecutter](https://cookiecutter.readthedocs.io/en/latest/)
Um utilitário de linha de comando que cria template de projetos Django. Uma alternativa ao template criado ao se executar `python django-admin.py startproject meuprojeto .` Parece interessante e tem a proposta de deixar mais organizado e funcional!

**Comment by Riverfount** [comment]
[super()](http://sixty-north.com/blog/series/pythons-super-explained)

Série de artigos explanando sobre o uso do `super()`!

**Comment by beatrizuezu** [comment]
[Visualizando query SQL a partir da ORM do Django](https://medium.com/@beatrizuezu/visualizando-query-sql-a-partir-do-orm-django-5771370a9c55)

Como visualizar query SQL da ORM do Django
 * Repositório utilizado [https://github.com/beatrizuezu/de-sql-para-orm-django](https://github.com/beatrizuezu/de-sql-para-orm-django)

**Comment by henriquebastos** [comment]
Python-tesseract is a python wrapper for google's Tesseract-OCR
https://pypi.python.org/pypi/pytesseract
Use Python para reconhecer caracteres em documentos.

**Comment by henriquebastos** [comment]
Google Mobile Vision
https://developers.google.com/vision/
Detecte objetos em fotos e vídeos diretamente do seu mobile.

**Comment by henriquebastos** [comment]
Extraindo texto de imagens com Python
http://pythonclub.com.br/extraindo-texto-de-imagens-com-python.html
Um passo a passo bem maneiro redigido pela galera do PythonClub.

**Comment by henriquebastos** [comment]
Amazon Rekognition
https://aws.amazon.com/pt/rekognition/
Reconhecimento de imagem com base em deep learning.

**Comment by augustogoulart** [comment]
[https://helabs.com/blog/time-proprio-ou-time-sob-demanda](https://helabs.com/blog/time-proprio-ou-time-sob-demanda/)
Entenda melhor as opções e como encaixar sua empresa em uma delas.

**Comment by davinirjr** [comment]
http://blog.payoneer.com/freelancers/industry-tips-fl/13-high-demand-freelancer-skills/

Levantamento da Payoneer sobre as 13 habilidades mais requeridas para freelancing.

**Comment by henriquebastos** [comment]
Django single file project
http://mlvin.xyz/django-single-file-project.html
Um projeto Django inteiramente funcional com apenas 1 arquivo.

**Comment by henriquebastos** [comment]
A Guide to Becoming a Full-Stack Developer in 2017
https://medium.com/coderbyte/a-guide-to-becoming-a-full-stack-developer-in-2017-5c3c08a1600c
Um guia sobre o que é preciso para se tornar um desenvolvedor "full stack" em 2017.

**Comment by Lrcezimbra** [comment]
**[Python Fire](https://github.com/google/python-fire)**
Biblioteca que cria um CLI _automagicamente_ a partir de um objeto Python
